# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kiosk Tech Monthly
email: hardrefresh@kiosk.tm
description: Did you try a hard refresh?
baseurl: "" # the subpath of your site, e.g. /blog
url: "amylaun.github.io" # the base hostname & protocol for your site
twitter_username: kiosktm
github_username:  amylaun

# Build settings
markdown: kramdown

gems: [jekyll-assets, autoprefixer-rails]

assets:
  sources:
    - _assets/javascripts
    - _assets/stylesheets
  autoprefixer:
    browsers: ["last 2 versions","> 5%","IE 9"]
