# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kiosk Tech Monthly
email: hardrefresh@kiosk.tm
description: Did you try a hard refresh?
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://amylaun.github.io" # the base hostname & protocol for your site
twitter_username: amypotato
github_username:  amylaun

# Build settings
markdown: kramdown
permalink: "/:year-:month-:day/"

gems:
  - octopress-autoprefixer
  - contentful
  - jekyll-contentful-data-import

contentful:
  spaces:
    - notes: # Jekyll _data folder identifier - Required
        space: qvfiijf2rzky        # Required
        access_token: 15635f10b8df1908918745719c5fd639c981223a3b8226b282bbddbe8a8348a9 # Required
        client_options:            # Optional
          api_url: 'preview.contentful.com' # Defaults to 'api.contentful.com' which is Production
