# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kiosk Tech Monthly
email: hardrefresh@kiosk.tm
description: Did you try a hard refresh?
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://amylaun.github.io" # the base hostname & protocol for your site
twitter_username: amypotato
github_username:  amylaun

# Build settings
markdown: kramdown

gems:
  - octopress-autoprefixer
